[book]
title = "sift"
authors = ["talkincode"]
language = "en"
src = "docs"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/talkincode/sift"
edit-url-template = "https://github.com/talkincode/sift/edit/master/{path}"
site-url = "/sift/"
additional-css = ["docs/theme/language.css"]
additional-js = ["docs/theme/language.js"]
